# Generated by Django 5.0.14 on 2026-07-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')])),
                ('external_pack_id', models.IntegerField()),
                ('price_in_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='credential',
            new_name='api_credent_order_i_ec43c7_idx',
            old_name='api_credential_order_idx',
        ),
        migrations.RenameIndex(
            model_name='credittransaction',
            new_name='api_creditt_reselle_d36bc9_idx',
            old_name='api_credittrans_reseller_created_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='api_customu_role_3dda3d_idx',
            old_name='api_customuser_role_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_reselle_cd4351_idx',
            old_name='api_order_reseller_created_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_is_acti_b97ca3_idx',
            old_name='api_product_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_categor_07b5d3_idx',
            old_name='api_product_category_idx',
        ),
        migrations.RenameIndex(
            model_name='quarantinedcredential',
            new_name='api_quarant_resolve_5514bf_idx',
            old_name='api_quarantined_resolved_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='duration_months',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_pack_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_in_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'duration_months')},
        ),
    ]
