# Generated by Django 5.0.14 on 2026-07-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_data_migration_master_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='streaming_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
