# Generated by Django 5.0.14 on 2026-07-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_populate_categories_and_provider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_is_acti_b97ca3_idx',
            old_name='api_product_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_is_acti_4ed87d_idx',
            old_name='api_product_cat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_search__d4f0fe_gin',
            old_name='api_product_search_gin_idx',
        ),
    ]
