# Generated by Django 5.0.14 on 2026-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_api_product_is_active_idx_api_product_is_acti_b97ca3_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'external_pack_id')},
        ),
        migrations.AddField(
            model_name='credential',
            name='m3u_url',
            field=models.CharField(blank=True, default='', help_text='Full M3U playlist URL (separate from base DNS domain).', max_length=500),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_lifetime',
            field=models.BooleanField(default=False, help_text='Check for subscriptions that never expire (e.g. HotPlayer FOREVER).'),
        ),
        migrations.AddField(
            model_name='provider',
            name='adapter_key',
            field=models.CharField(choices=[('neo4k', 'NEO 4K'), ('hotplayer', 'HotPlayer'), ('mock', 'Mock')], default='mock', help_text='Determines which adapter class handles API calls for this provider.', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific config (e.g. {"dns_domain": "kmapp.xyz", "port": 8080}).'),
        ),
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Null for Lifetime subscriptions.', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='duration_months',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')], help_text='Leave blank for Lifetime variants.', null=True),
        ),
    ]
