# Generated by Django 5.0.14 on 2026-07-06 13:03

import os
from django.db import migrations


def seed_default_provider(apps, schema_editor):
    Provider = apps.get_model('api', 'Provider')
    Product = apps.get_model('api', 'Product')
    from api.utils import encrypt_password
    
    if Provider.objects.filter(slug='neo4k').exists():
        return
        
    api_endpoint = os.environ.get('IPTV_API_URL', 'https://4k.cms-only.ru/api/api.php')
    api_token = os.environ.get('IPTV_API_KEY', '')
    dns_domain = os.environ.get('IPTV_DNS', 'kmapp.xyz')
    port = int(os.environ.get('IPTV_PORT', 8080))
    
    provider = Provider.objects.create(
        name='NEO 4K',
        slug='neo4k',
        adapter_key='neo4k',
        api_endpoint=api_endpoint,
        api_token=encrypt_password(api_token) if api_token else None,
        extra_config={
            'dns_domain': dns_domain,
            'port': port
        },
        is_active=True
    )
    
    Product.objects.filter(provider__isnull=True).update(provider=provider)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_multi_provider_schema'),
    ]

    operations = [
        migrations.RunPython(seed_default_provider, reverse_code=migrations.RunPython.noop),
    ]
