# Generated by Django 5.0.14 on 2026-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_seed_default_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible JSONB store for non-secret credential data (MAC, M3U URL, license key, etc.).'),
        ),
    ]
