# Generated by Django 5.0.14 on 2026-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_credential_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='adapter_key',
            field=models.CharField(choices=[('neo4k', 'NEO 4K'), ('goldpanel', 'Gold Panel'), ('hotplayer', 'HotPlayer'), ('mock', 'Mock')], default='mock', help_text='Determines which adapter class handles API calls for this provider.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'external_pack_id', 'duration_months')},
        ),
    ]
