# Generated by Django 5.0.14 on 2026-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_provider_adapter_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration_months',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (24, '2 Years'), (36, '3 Years')], null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='duration_months',
            field=models.IntegerField(blank=True, choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (24, '2 Years'), (36, '3 Years')], help_text='Leave blank for Lifetime variants.', null=True),
        ),
    ]
