# Generated by Django 5.0.14 on 2026-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_trial_duration_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='adapter_key',
            field=models.CharField(choices=[('neo4k', 'NEO 4K'), ('goldpanel', 'Gold Panel'), ('hotplayer', 'HotPlayer'), ('golden_api', 'Golden API'), ('tivipanel', 'TiviPanel'), ('mock', 'Mock')], default='mock', help_text='Determines which adapter class handles API calls for this provider.', max_length=20),
        ),
    ]
