# Generated by Django 5.0.14 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_provider_adapter_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='adapter_key',
            field=models.CharField(choices=[('neo4k', 'NEO 4K'), ('goldpanel', 'Gold Panel'), ('hotplayer', 'HotPlayer'), ('golden_api', 'Golden API'), ('tivipanel', 'TiviPanel'), ('promax', 'Promax'), ('mock', 'Mock')], default='mock', help_text='Determines which adapter class handles API calls for this provider.', max_length=20),
        ),
    ]
