# Generated by Django 5.0.14 on 2026-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_provider_adapter_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='credential_type',
            field=models.CharField(blank=True, choices=[('username_password', 'Username + Password'), ('single_code', 'Single Code')], help_text='Required for manual products. Defines the credential input format.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if this product requires manual credential assignment (no API).'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['streaming_username'], name='api_credent_streami_f4295f_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['order', 'is_revoked'], name='api_credent_order_i_2c2d24_idx'),
        ),
    ]
