# Generated by Django 5.0.14 on 2026-07-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_15_months_and_variant_to_manual_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number for receiving order notifications (admin only).', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='adapter_key',
            field=models.CharField(choices=[('neo4k', 'NEO 4K'), ('goldpanel', 'Gold Panel'), ('hotplayer', 'HotPlayer'), ('golden_api', 'Golden API'), ('tivipanel', 'TiviPanel'), ('promax', 'Promax'), ('redfoxx', 'Redfoxx'), ('whatsapp', 'WhatsApp'), ('mock', 'Mock')], default='mock', help_text='Determines which adapter class handles API calls for this provider.', max_length=20),
        ),
    ]
