# Generated by Django 5.0.14 on 2026-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_whatsapp_phone_and_adapter_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='external_pack_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
