# Generated by Django 5.0.14 on 2026-07-18 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_15_months_and_variant_to_manual_credential'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualproductcredential',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='The duration variant this credential is tied to. Null for legacy/universal credentials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_credentials', to='api.productvariant'),
        ),
        migrations.AddIndex(
            model_name='manualproductcredential',
            index=models.Index(fields=['product', 'variant', 'status'], name='dashboard_m_product_58df25_idx'),
        ),
    ]
