# Generated by Django 5.0.14 on 2026-07-19 02:38

from django.db import migrations, models


def convert_assigned_to_available(apps, schema_editor):
    ManualProductCredential = apps.get_model('dashboard', 'ManualProductCredential')
    ManualProductCredential.objects.filter(status='assigned').update(status='available')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_15_months_and_variant_to_manual_credential'),
    ]

    operations = [
        migrations.RunPython(convert_assigned_to_available, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='manualproductcredential',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
